name = "Craftoria"
author = "TeamAOE"
version = "1.21.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3f237628511837904eae0dcda10b07beb11a27633879b8226bacc95dd1a6c77"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.173"
